"""admin panel schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-03-20 17:47:57.278100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index('ix_project_aliases_alias', 'project_aliases', ['alias'], unique=True)
    op.create_table('project_prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('classification_prompt_text', sa.Text(), nullable=True),
    sa.Column('routing_prompt_text', sa.Text(), nullable=True),
    sa.Column('examples_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_prompt_versions_project_id_is_active', 'project_prompt_versions', ['project_id', 'is_active'], unique=False)
    op.create_index('ix_project_prompt_versions_project_id_version_no', 'project_prompt_versions', ['project_id', 'version_no'], unique=True)
    op.create_table('system_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('subsystem', sa.String(length=50), nullable=False),
    sa.Column('task_item_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_item_id'], ['task_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_events_created_at', 'system_events', ['created_at'], unique=False)
    op.create_index('ix_system_events_event_type', 'system_events', ['event_type'], unique=False)
    op.alter_column('daily_review_snapshots', 'payload_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('task_revisions', 'proposal_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_revisions', 'proposal_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('daily_review_snapshots', 'payload_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_system_events_event_type', table_name='system_events')
    op.drop_index('ix_system_events_created_at', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index('ix_project_prompt_versions_project_id_version_no', table_name='project_prompt_versions')
    op.drop_index('ix_project_prompt_versions_project_id_is_active', table_name='project_prompt_versions')
    op.drop_table('project_prompt_versions')
    op.drop_index('ix_project_aliases_alias', table_name='project_aliases')
    op.drop_table('project_aliases')
    # ### end Alembic commands ###
